// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8iCtAC9VgNi3CQ5BqxPUlDBFa0aC1hvA',
    appId: '1:689506937494:web:cdb3bf2d1ec0ab2a1bf0b7',
    messagingSenderId: '689506937494',
    projectId: 'abiad-9ae45',
    authDomain: 'abiad-9ae45.firebaseapp.com',
    storageBucket: 'abiad-9ae45.appspot.com',
    measurementId: 'G-CHST04PB4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3uXSdhfQy-3naadHIOpxWQA3gPYQ_jQw',
    appId: '1:689506937494:android:730ac2ba61a024c01bf0b7',
    messagingSenderId: '689506937494',
    projectId: 'abiad-9ae45',
    storageBucket: 'abiad-9ae45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_GhwfjMXk6ArYres0LKvkR_-ndFKmwA',
    appId: '1:689506937494:ios:9d6e81c2c5a7c7c61bf0b7',
    messagingSenderId: '689506937494',
    projectId: 'abiad-9ae45',
    storageBucket: 'abiad-9ae45.appspot.com',
    iosBundleId: 'com.example.batal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd_GhwfjMXk6ArYres0LKvkR_-ndFKmwA',
    appId: '1:689506937494:ios:04a9fd9860394ef61bf0b7',
    messagingSenderId: '689506937494',
    projectId: 'abiad-9ae45',
    storageBucket: 'abiad-9ae45.appspot.com',
    iosBundleId: 'com.example.batal.RunnerTests',
  );
}
